on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps :
    
name : Deploy imx buy bot
    uses : appleboy/ssh-action@v0.1.2
    with :
      host: ${{secrets.SSH_HOST}}
      key: ${{secrets.SSH_KEY}}
      username: ${{secrets.SSH_USERNAME}}
      script: |
        cd /var/www/imx-buy-bot
        git pull git@github.com:nathanszig/imx-buy-bot.git
        pm2 reload "yarn -s buy-eth >> /home/nathan/logs/buy-eth.log"
        pm2 reload "yarn -s buy-imx >> /home/nathan/logs/buy-imx.log"
        pm2 reload "yarn -s buy-usdc >> /home/nathan/logs/buy-usdc.log"
        echo "Deploy OK"