on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps :
      - name : Deploy rendu
        uses : appleboy/ssh-action@v0.1.2
        with :
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/rendu
            git pull git@github.com:Alexguillemin91/imx-buy-bot.git
            pm2 delete all
            pm2 start "yarn -s buy-eth >> /home/alexguiguilebg/logs/buy-eth.log"
            echo "Deploy OK"
